# 应用名称
spring:
  datasource:
    url: jdbc:mysql://106.52.38.218:3306/online_motion?characterEncoding=UTF-8
    username: online_motion
    password: nneP3N26E6Bphrj6
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
#    call-setters-on-nulls: true
  type-aliases-package: com.codezl.onlinemotion.pojo.entity

#mybatis:
#  typeAliasesPackage: com.codezl.onlinemotion.pojo.entity
#  mapperLocations: classpath:mapper/*.xml
#  configuration:
#    map-underscore-to-camel-case: true

